language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.2.5"

before_install:
 - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
  - cd src
  - xbuild Nerve.sln
  - chmod +x packages/Machine.Specifications-Signed.0.7.0/tools/mspec-clr4.exe
  - mono --runtime=v4.0.30319 packages/Machine.Specifications-Signed.0.7.0/tools/mspec-clr4.exe specs/Nerve.Core.Specs/bin/Debug/Nerve.Core.Specs.dll
